import splash from "assets/splash.png";
import test from "assets/test.mp3";
import cat from "assets/cat.png";
import lvl99 from "assets/lvl99.mp3";
import hypersynthetic from "assets/hypersynthetic.mp3";
import showMeHow from "assets/showMeHow.mp3";
import nyaaBeach from "assets/nyaaBeach.jpg";
import tutorial0 from "assets/tutorial_0.png";
import tutorial1 from "assets/tutorial_1.png";
import tutorial2 from "assets/tutorial_2.png";
import logo from "assets/logo.png";
import profileCard from "assets/ProfileCard.png";
import cat1 from "assets/Cat1.png";
import cat2 from "assets/Cat2.png";
import cat3 from "assets/Cat3.png";
import cat4 from "assets/Cat4.png";

export const splashURL = splash;
export const testURL = test;
export const catURL = cat;
export const lvl99URL = lvl99;
export const hypersyntheticURL = hypersynthetic;
export const showMeHowURL = showMeHow;
export const nyaaBeachURL = nyaaBeach;
export const tutorial0URL = tutorial0;
export const tutorial1URL = tutorial1;
export const tutorial2URL = tutorial2;
export const logoURL = logo;
export const profileCardURL = profileCard;
export const cat1URL = cat1;
export const cat2URL = cat2;
export const cat3URL = cat3;
export const cat4URL = cat4;