require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/.pnpm/@capacitor+ios@4.4.0_@capacitor+core@4.4.0/node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/.pnpm/@capacitor+ios@4.4.0_@capacitor+core@4.4.0/node_modules/@capacitor/ios'
  pod 'CapacitorFirebaseMessaging', :path => '../../node_modules/.pnpm/@capacitor-firebase+messaging@1.2.0_xjtau353dze36oiw2mzz4sxcni/node_modules/@capacitor-firebase/messaging'
  pod 'CapacitorCamera', :path => '../../node_modules/.pnpm/@capacitor+camera@4.1.3_@capacitor+core@4.4.0/node_modules/@capacitor/camera'
  pod 'CapacitorDialog', :path => '../../node_modules/.pnpm/@capacitor+dialog@4.0.1_@capacitor+core@4.4.0/node_modules/@capacitor/dialog'
  pod 'CapacitorKeyboard', :path => '../../node_modules/.pnpm/@capacitor+keyboard@4.0.1_@capacitor+core@4.4.0/node_modules/@capacitor/keyboard'
  pod 'CapacitorLocalNotifications', :path => '../../node_modules/.pnpm/@capacitor+local-notifications@4.1.2_@capacitor+core@4.4.0/node_modules/@capacitor/local-notifications'
  pod 'CapacitorNetwork', :path => '../../node_modules/.pnpm/@capacitor+network@4.0.1_@capacitor+core@4.4.0/node_modules/@capacitor/network'
  pod 'CapacitorPreferences', :path => '../../node_modules/.pnpm/@capacitor+preferences@4.0.1_@capacitor+core@4.4.0/node_modules/@capacitor/preferences'
  pod 'CapacitorPushNotifications', :path => '../../node_modules/.pnpm/@capacitor+push-notifications@4.1.1_@capacitor+core@4.4.0/node_modules/@capacitor/push-notifications'
  pod 'CapacitorShare', :path => '../../node_modules/.pnpm/@capacitor+share@4.0.1_@capacitor+core@4.4.0/node_modules/@capacitor/share'
  pod 'CapacitorSplashScreen', :path => '../../node_modules/.pnpm/@capacitor+splash-screen@4.1.1_@capacitor+core@4.4.0/node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../../node_modules/.pnpm/@capacitor+status-bar@4.0.1_@capacitor+core@4.4.0/node_modules/@capacitor/status-bar'
  pod 'CapacitorToast', :path => '../../node_modules/.pnpm/@capacitor+toast@4.0.1_@capacitor+core@4.4.0/node_modules/@capacitor/toast'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'Firebase/Messaging' # Add this line
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Alamofire'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
